### ISSUE TITLE
Updated sample config

### ISSUE THREAD

**Issue by solarchemist** [sainathadapa/i3-wm-multi-disp-scripts#3]
This is a very useful collection of scripts you've created @sainathadapa. I've only been using it for the last hour or so on my multi-monitor i3 setup, but it already feels like a big difference and exactly what I was hoping to achieve with i3. Kudos!

For other new users, the sample i3 config at the end of your README should be updated to reflect the changed filenames in your repo.
I used `git log --format="%H" --name-only --follow -- <filename>` to find out each file's filename history:
```
quickswitch.py                         -->   bring_container_to_current_workspace.py
newProjectWorkspaces.py                -->   create_new_project.py
cycleContainerProjectWorkspaces.py     -->   move_current_container_to_next_workspace_in_project.py
cycleProjectWorkspacesOutput.py        -->   move_workspaces_in_project_to_next_output.py
renameProject.py                       -->   rename_project.py
switchNextProject.py                   -->   switch_to_next_project.py
cycleProjectWorkspacesFocus.py         -->   switch_to_next_wk_in_project.py
```

Here's an updated sample config using the current filenames and assuming `~/.config/i3/`:
```
# project workflow bindings
bindsym $mod+Shift+p     exec python3 ~/.config/i3/i3-wm-multi-disp-scripts/create_new_project.py
bindsym $mod+p           exec python3 ~/.config/i3/i3-wm-multi-disp-scripts/switch_to_next_project.py
bindsym $mod+Tab         exec python3 ~/.config/i3/i3-wm-multi-disp-scripts/switch_to_next_wk_in_project.py
bindsym $mod+Shift+Tab   exec python3 ~/.config/i3/i3-wm-multi-disp-scripts/move_workspaces_in_project_to_next_output.py
bindsym $mod+Control+Tab exec python3 ~/.config/i3/i3-wm-multi-disp-scripts/move_current_container_to_next_workspace_in_project.py
bindsym $mod+n           exec python3 ~/.config/i3/i3-wm-multi-disp-scripts/rename_project.py

# create initial project on startup with project name 'default'
exec --no-startup-id python3 ~/.config/i3/i3-wm-multi-disp-scripts/create_new_project.py default
```

Sorry for opening an issue instead of a pull request - I haven't had time to learn how to use pull requests yet. Hope you find the updated sample config useful.

**Comment by sainathadapa** [comment]
Good to know that you found the config to be useful :)

I keep updating the config constantly, and so keeping the readme up-to-date is hard. I'll  review it once now. Thanks.
