### ISSUE TITLE
Multiple Workspaces per Monitor

### ISSUE THREAD

**Issue by santos-j** [sainathadapa/i3-wm-multi-disp-scripts#4]
First of all, this project is just amazing. Straight up tackling the lack of "contexts" in i3, very sexy.

I spent some time using your scripts, but I realised that there's no simple way to create and cycle through multiple workspaces per monitor in a single project. 

By that I mean, having a given "Project A", with workspaces "1" in output A and "2" in output B. Then, creating a new workspace "3", in any given output, let's say B. Finally going nuts, moving "3" to output A, cycling to workspace "2" in output A, and moving workspace "2" to output B, or whatever else pleases one's heart.

Is it just me being stupid, or is it not supported?

**Comment by sainathadapa** [comment]
I didn't fully understand your use case, but isn't `workspace next_on_output` enough for cycling through workspaces on a particular monitor?
